<select class="form-control lang selectpicker" data-width="100%" name="level" id="level">
	<option value="-1" selected="selected">Level</option>
	<option value="0">Starter</option>
	<option value="1">Elementary</option>
	<option value="2">Pre-Intermediate</option>
	<option value="3">Intermediate</option>
	<option value="4">Upper-Intermediate</option>
	<option value="5">Advanced</option>
	<option value="6">Proficient</option>
</select>