<!--	Copyright © 2015 - sayitagain.pw 
 	Author - Dmitry Kuznetsov		-->
<select class="form-control lang selectpicker" data-width="100%" data-live-search=”true” name="language" id="language">
<optgroup label="Language to talk">
	<option value="English" selected="selected">English</option>
	<option value="Mandarin">Mandarin</option>
	<option value="Spanish">Spanish</option>
	<option value="Russian">Russian</option>	
	<option value="German">German</option>
	<option value="Italian">Italian</option>
	<option value="French">French</option>
</optgroup>
</select>